// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqsky5LXq--L6c-vcGlHkTRsS8z4eOmfY',
    appId: '1:50311591029:web:be723540212a0b1960743c',
    messagingSenderId: '50311591029',
    projectId: 'dore-404520',
    authDomain: 'dore-404520.firebaseapp.com',
    databaseURL: 'https://dore-404520-default-rtdb.firebaseio.com',
    storageBucket: 'dore-404520.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcOr9gL876Iw9dYTOfVI1q305ccAmoYkw',
    appId: '1:50311591029:android:29dc279c5f8fd93060743c',
    messagingSenderId: '50311591029',
    projectId: 'dore-404520',
    databaseURL: 'https://dore-404520-default-rtdb.firebaseio.com',
    storageBucket: 'dore-404520.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_Ao9nA8M4nMWJsQt2neIOdi807ZpHkM',
    appId: '1:50311591029:ios:aa8362643951527a60743c',
    messagingSenderId: '50311591029',
    projectId: 'dore-404520',
    databaseURL: 'https://dore-404520-default-rtdb.firebaseio.com',
    storageBucket: 'dore-404520.appspot.com',
    iosBundleId: 'com.example.dore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_Ao9nA8M4nMWJsQt2neIOdi807ZpHkM',
    appId: '1:50311591029:ios:3f74cc2f6bedb6fb60743c',
    messagingSenderId: '50311591029',
    projectId: 'dore-404520',
    databaseURL: 'https://dore-404520-default-rtdb.firebaseio.com',
    storageBucket: 'dore-404520.appspot.com',
    iosBundleId: 'com.example.dore.RunnerTests',
  );
}
